raw:
  base_dir: "./data/raw"
  label_0_dir: "정상"
  label_0_csv: "smishing.csv"
  label_1_jsonl: "smishing_labeled_total_fix_relabel_v8_dedup.jsonl"

processed:
  base_dir: "./data/processed"
  label_0_jsonl: "label_0.jsonl"
  label_1_jsonl: "label_1.jsonl"

train:
  train_jsonl: "./data/train/train.jsonl"

val:
  val_jsonl: "./data/val/val.jsonl"
  output_jsonl: "./data/outputs/val_output.jsonl"

test:
  test_jsonl: "./data/test/test.jsonl"
  output_dir: "./data/outputs"

